config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :update]
  root to: 'homes#top'
  get "home/about" => "homes#about", as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   has_one_attached :image
   belongs_to :user

   validates :title, presence: true
   validates :body, presence: true
   validates :body,
    length: { minimum: 1, maximum: 200 }

   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :name,
    length: { minimum: 2, maximum: 20 }
  validates :introduction,
    length: { maximum: 50 }


  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = "You have updated user successfully."
    redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
     @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
    redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated user successfully."
       redirect_to book_path(@book.id)
    else
       render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

   private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
    redirect_to user_path(current_user)
    end
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    @books = @user.books
    redirect_to(user_path(current_user)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
   <h2>User info</h2>
   <%= image_tag user.get_profile_image(100,100) %>
   <table class="table">
    <tbody>
     <tr>
      <th>name</th>
      <th><%= user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
     </tr>
    </tbody>
   </table>
   <div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
   </div>
   <h2 class="mt-3">New book</h2>

  <%= form_with model: book do |f| %>
   <div class="form-group">
    <label for="book_title">Title</label>
     <%= f.text_field :title %>
   </div>
   <div class="form-group">
   <label for="book_opinion">Opnion</label>
   <br><%= f.text_area :body %>
   </div>
   <div class="form-group">
   <%= f.submit 'Create Book', class:"btn btn-success" %>
  </div>
  <% end %>
  </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
   <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
   <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

<%= form_with model: @book,url: book_path(@book.id), method: :patch do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <br><%= f.text_field :title %>
</div>

<div class="form-group">
 <label for="book_body">Opinion</label>
  <br><%= f.text_area :body %>
</div>

  <div class="form-group">
    <%= f.submit 'Update Book', class:"btn btn-success" %>
  </div>

  <span><%= link_to "Show", book_path(@book.id) %></span>
  <span>|</span>
  <span><%= link_to "Back", books_path %></span>


<% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<h2><% if @book.errors.any? %>
   <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
   <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</h2>
<div class="container px-5 px-sm-0">
 <div class="row">
 <%= render 'list', book: @book, user: @user %>

<div class="col-md-8 offset-md-1">
 <h2>Books</h2>
  <table class="table table-hover table-inverse">
   <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
   </thead>
  <% @books.each do |book| %>
  <tbody>
   <tr>
    <td>
     <%= link_to user_path(book.user) do %>
    <%= image_tag book.user.get_profile_image(80,80) %>
    <% end %>
    </td>
    <td> <%= link_to book.title, book_path(book.id) %></td>
    <td> <%= book.body %></td>
   </tr>
  </tbody>
  <% end %>
 </table>
</div>
</div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
  <%= form_with model: @book do |f| %>
    <div class="form-group">
     <label for="book_title">Title</label>
     <%= f.text_field :title %>
    </div>
    
    <div class="form-group">
     <label for="book_Opinion">Opinion</label>
     <%= f.text_area :body %>
    </div>
    
    <div class="form-group">
     <%= f.submit 'Create Book' %>
     <% end %>
    </div>
  

app/views/books/show.html.erb
<h2><% if @book_new.errors.any? %>
   <%= @book_new.errors.count %>error prohibited this obj from being saved:
    <ul>
   <% @book_new.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</h2>
<div class="container">
 <div class="row">
 <%= render 'list', book: @book_new, user: @user %>
  <div class="col-md-8 offset-md-1">

<h2>Book detail</h2>
<table class="table">
 <thead>
  <tr>
   <td>
    <%= link_to user_path(@book.user.id) do %>
    <%= image_tag @book.user.get_profile_image(100,100) %>
    <br><%= @book.user.name %>
    <% end %>
   </td>
   <td> <%= @book.title %></td>
   <td> <%= @book.body %></td>
   <% if @book.user == current_user %>
    <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
    <td><%= link_to "Destroy", book_path(@book), method: :delete , class:"btn btn-sm btn-danger" %></td>
  <% end %>
  </tr>
 </thead>
</table>

app/views/homes/about.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
              welcome to
              <i class="fas fa-book"></i>
              <strong>Bookers</strong>
              !!
            </h1>
          </div>
        </div>
      </div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
     <h1>
      welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
       !!
     </h1>
      <p>you can share and exchange your opinions,inpressions,and emotions</p>
      <p>about various books!</p>
       <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
         </div>
       </div>
     </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/ecbd652d7d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class ="navbar navbar-expand-lg navbar-dark bg-dark">
    <% if user_signed_in? %>

       <div class = "container">
        <a class="navbar-brand" href="/">
         <span>Bookers</span>
        </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
            <li>
             <%= link_to user_path(current_user), class: "nav-link text-light" do %>
             <i class="fas fa-home"></i>
              Home
             <% end %>
            </li>

            <li>
             <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>
               Users
             </a>
            </li>

            <li>
             <a class="nav-link text-light" href="/books">
              <i class="fas fa-book-open"></i>
               Books
             </a>
            </li>

            <li>
             <a class="nav-link text-light" rell="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>
               Log out
             </a>
            </li>
           </ul>
          </div>
        </div>
    <% else %>
         <div class = "container">
           <a class="navbar-brand" href="/">
            <span>Bookers</span>
           </a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <li>
             <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>
               Home
             </a>
            </li>

            <li>
             <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>
               About
             </a>
            </li>

            <li>
             <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>
               Sign up
             </a>
            </li>

            <li>
             <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>
               Log in
             </a>
            </li>
            <% end %>
        </ul>
       <div>
      </div>
     </nav>
    </header>
   <main class="mb-auto">
    <%= flash[:notice] %>
    <%= yield %>
  </main>
 <footer>
   <div class="container mt-5">
     <div class="row">
       <div class="mx-auto">
        <p>CopyRight Inflatop.inc</p>
       </div>
     </div>
   </div>
 </footer>
</body>
</html>

app/views/users/edit.html.erb
<h2>
<% if @user.errors.any? %>
   <%= @user.errors.count %>error prohibited this obj from being saved:
    <ul>
   <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</h2>

<div class="container">
 <div class="row">
   <div class="col-sm12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>

   <%= form_with model: @user do |f| %>
   <div class="form-group">
   <label for="inputName">Name</label>
   <br><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  </div>

  <div class="form-group">
  <label for="inputImage">Image</label>
  <br><%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %>
  </div>

  <div class="form-group">
  <label for="introduction">Introduction</label>
  <br><%= f.text_area :introduction %>
  </div>

  <div class="form-group">
  <%= f.submit "Update User", class:"btn btn-secondary" %>
  </div>
 <% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <%= render 'books/list', book: @book, user: @user %>
  <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table">
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
    </thead>
  <% @users.each do |user| %>
    <tbody>
     <tr>
      <td><%= image_tag user.get_profile_image(80,80) %></td>
      <td><%= user.name %></td>
      <td>
      <%= link_to "Show", user_path(user.id) %>
      </td>
     </tr>
    </tbody>
  <% end %>
   </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<% if @book.errors.any? %>
   <%= @book.errors.count %>error prohibited this obj from being saved:
    <ul>
   <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
 <div class="row">
<%= render 'books/list', book: @book, user: @user %>
  <div class="col-md-8 offset-md-1">

  <h2>Books</h2>
  <table class="table table-hover table-inverse">
   <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
   </thead>
  <tbody>
   <% @books.each do |book| %>
   <tr>
    <td>
     <%= link_to user_path(@user) do %>
     <%= image_tag @user.get_profile_image(80,80) %><% end %></td>
    <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
   </tr>
   <% end %>
 </tbody>
</table>
  </div>
 </div>
</div>